In [43]:
import numpy as np
# try platform
xrange?
a=range(1,5, 2)
b=np.zeros(5)
print a
for a in range(5):
    b[a]=(a-1)**2
    print a
print b
print np.dot(b,2)+1
print b.shape
print b.T + b
a = np.array([[1,4],[3,1]])
c=enumerate(b)
print c

[1, 3]
0
1
2
3
4
[ 1.  0.  1.  4.  9.]
[  3.   1.   3.   9.  19.]
(5,)
[  2.   0.   2.   8.  18.]


In [85]:
aa=b
print b
print np.argsort(b)
# c=np.argsort(b)
aa[np.argsort(b)]
# b[:3]
# np.bincount == accumarray 
# np.bincount(b)

[ 0.18088441  0.56380001  0.65960807  0.62562556  0.78186825  0.77854562
  0.59856871  0.99308192  0.81817161  0.17230587]
[9 0 1 6 3 2 5 4 8 7]


array([ 0.17230587,  0.18088441,  0.56380001,  0.59856871,  0.62562556,
        0.65960807,  0.77854562,  0.78186825,  0.81817161,  0.99308192])

In [92]:
unique, counts = np.unique(xrange(5), return_counts=True)
print unique
print counts
# dict(zip(unique, counts))

[0 1 2 3 4]
[1 1 1 1 1]


In [61]:
a=np.random.rand(5)
b=np.random.rand(10)
c=np.zeros((5,10))
for i in xrange(len(a)):
    for j in xrange(len(b)):
        c[i,j]=(a[i]-b[j])**2
print c

[[  4.06103128e-04   1.31597431e-01   2.10287972e-01   1.80275943e-01
    3.37365631e-01   3.33516893e-01   1.58031933e-01   6.27336090e-01
    3.80855857e-01   8.25444158e-04]
 [  7.36764684e-04   1.26573853e-01   2.03924727e-01   1.74387870e-01
    3.29292845e-01   3.25490567e-01   1.52522191e-01   6.16309942e-01
    3.72275448e-01   1.27605792e-03]
 [  5.95518212e-01   1.51151959e-01   8.58341161e-02   1.06900957e-01
    2.91434134e-02   3.02888946e-02   1.25325884e-01   1.64018889e-03
    1.80663339e-02   6.08831898e-01]
 [  3.07456014e-02   4.30858718e-02   9.20390776e-02   7.25746952e-02
    1.81169075e-01   1.78351630e-01   5.87287086e-02   4.05582092e-01
    2.13391303e-01   3.38275891e-02]
 [  2.85068381e-02   3.04433894e-01   4.19338288e-01   3.76481433e-01
    5.92628261e-01   5.87523625e-01   3.44010387e-01   9.62433972e-01
    6.49840553e-01   2.56836324e-02]]


In [93]:
c=np.random.rand(3,5)
d=np.sum(c,axis = 0)
print d.shape
f=np.sum(c,axis = 1)
print f.shape
f.reshape(3,1) + d.reshape(1,5)
a=np.random.rand(5)
a[np.argsort(a)]
# np.random.rand(5,1)+np.random.rand(1,5)

(5,)
(3,)


array([ 0.1496504 ,  0.5986571 ,  0.8356232 ,  0.91389876,  0.9308299 ])

In [95]:
a=xrange(5)
b=xrange(3)
print a-b

TypeError: unsupported operand type(s) for -: 'xrange' and 'xrange'

In [ ]:
a=np.random.rand(50)
b=np.random.rand(50,500)#np.array_split(xrange(len(a)),5)
lb=np.shape[b]
num_folds = 5
print lb
# print a[b[0]]
print np.array_split(xrange(lb[0]),num_folds)
a={}
a[1]=np.ones(5)
print a
a[1][2]=2
print a

In [130]:
a = np.random.rand(2,3)
N = a.shape[0]
b= a.reshape(N,-1)

print np.max(a, axis=1, keepdims=True)

[[ 0.92331658]
 [ 0.92886608]]
