In [107]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

In [35]:
aa=np.random.rand(5,3)
print aa.shape[1]
np.zeros?
aa=np.zeros(5)
print aa.shape

3
(5,)


In [54]:
# tile?
z=(np.array(range(5))-5)**2
print np.multiply(z.T,z)

[625 256  81  16   1]


In [ ]:
z=np.random.rand(5,3)
print z[1,] 
print z[1,:]

In [ ]:
a=None
print a

In [18]:
a=np.random.rand(5,5)
b=np.random.randint(4,size=(5,1))
print a
print b
print np.dot(np.reshape(a[2,:],(-1,1)),np.random.rand(1,2)>0.5)

[[ 0.75514786  0.20879094  0.29851978  0.70795505  0.28048613]
 [ 0.16674569  0.51538673  0.11150855  0.42083281  0.54728341]
 [ 0.59937214  0.30156423  0.04235579  0.19781365  0.06782956]
 [ 0.12394216  0.62938337  0.57176646  0.63501175  0.28357674]
 [ 0.11983777  0.4032881   0.60426782  0.2454673   0.60565846]]
[[3]
 [2]
 [1]
 [0]
 [2]]
[[ 0.          0.59937214]
 [ 0.          0.30156423]
 [ 0.          0.04235579]
 [ 0.          0.19781365]
 [ 0.          0.06782956]]


In [25]:
a= np.random.rand(5,3)
print a[:,1]
a[:,1]*np.sum(np.random.rand(1,5)>.5)
np.zeros((2,1))

[ 0.20513519  0.67691556  0.21996343  0.06027013  0.89823397]


array([[ 0.],
       [ 0.]])

In [60]:
np.argmax?
a = np.random.rand(5,3) - np.ones((5,1)) #(:,np.ones((5,1))
print np.random.randint(3,size=(5,1))
print np.arange(a.shape[0])
a[np.arange(a.shape[0]), np.random.randint(3,size=5)]=np.random.rand(5)
print a 

[[2]
 [2]
 [0]
 [1]
 [0]]
[0 1 2 3 4]
[[ -5.37993466e-04  -5.47006694e-01   4.64067510e-01]
 [ -1.17904024e-01  -4.82457290e-01   2.16195698e-01]
 [ -8.08017946e-01   8.81966587e-01  -6.59700458e-01]
 [ -6.72297784e-01   6.94691495e-01  -8.99912798e-01]
 [  2.64991079e-01  -1.01918237e-01  -5.87314062e-01]]


In [78]:
reg=5
lr=3
a= {}
a[(reg,lr)]=[0 ,1]
aa, bb = a[(reg,lr)]
print aa
print bb
print np.exp(1

SyntaxError: invalid syntax (<ipython-input-78-b4213fa0b4e9>, line 8)

In [98]:
A= np.random.rand(3,5)/(np.arange(5)+1)
A*np.reshape(np.sum(A,axis=1), (-1,1))
%matplotlib inline?

Object `inline` not found.


In [101]:
dW11 = np.dot(X.T, (L2/np.reshape(np.sum(L2,axis=1),(-1,1)) -cscores).dot(W2.T))

NameError: name 'X' is not defined

In [ ]:
a={'abs':2, 'gg': 5}
print a['abs']

In [ ]:
if?